README.md

> 연관된 이슈를 작성해주세요.
> 프로젝트 팀 컨벤션을 리드미에 추가하였습니다.

docs : project readme for convention 

---

src/app/layout.tsx
src/app/protest/[id]/page.tsx
src/components/KakaoMaps/KakaoMap.tsx
src/components/Verification/Verification.tsx
src/hooks/useGeoLocation.tsx
src/lib/API/VerifyLocation.tsx
src/types.ts

- geolocation 을 통한 사용자 위치 가져오기
- 유저의 동의 여부에 따른 서버로의 위치 전송(현재 버튼 클릭 시 바로 동의 한 것으로 간주, 수정 예정)
- 서버의 응답값에 따른 인증 처리(응답 값을 가져와 처리하는 ui 미구현)

Feature verification

---

src/app/(with-hamburger-button)/page.tsx
src/app/globals.css
src/app/layout.tsx
src/app/protest/[id]/page.tsx
src/components/Footer/Footer.module.css
src/components/Footer/index.tsx
src/components/Header/Header.module.css
src/components/Header/index.tsx
src/components/Protest/protest-list.tsx
src/lib/utils.ts

> #3 
- 날짜 및 시간 형식 변경 (`yy년 m월 n일 pm/am hh시 mm분`)  
- 예상 참가 인원 숫자 포맷 변경 (1,000 단위 쉼표 추가)  

refactor : refactor protest detail UI for apply feedback

---

src/app/api/revalidate/protests/route.ts

- when called every cache is deleted
- going to be chaned to specific cache deletion

feat: added api for cache revalidation

---

package.json
pnpm-lock.yaml
src/app/protest/[id]/page.tsx
src/components/Protest/protest-card.tsx
src/components/Protest/protest-list.tsx
src/components/ui/sheet.tsx
tailwind.config.ts

minor fixes done to UI
- protest list height changed to meet addition of header and footer
- signature color changed to #D44646

fix: changed height of protest list and signature color

---

src/app/layout.tsx
src/components/GoogleAnalytics/GoogleAnalytics.tsx

구글 에널리틱스 삽입
- 애널리틱스 스크립트를 로드하고 초기화 하는 별도의 GoogleAnalytics 컴포넌트 생성
- 해당 컴포넌트를 최상단 layout에서 사용

Feature google analytics

---

package.json
pnpm-lock.yaml
src/app/(with-hamburger-button)/page.tsx
src/app/@modal/(.)protest/[id]/page.tsx
src/app/protest/[id]/page.tsx
src/components/Footer/Footer.module.css
src/components/Header/Header.module.css
src/components/KakaoLogin/KakaoLogin.tsx
src/components/Protest/protest-card.tsx
src/components/Protest/protest-list.tsx
src/components/Protest/protest-md.tsx
src/components/Verification/Verification.tsx
src/components/ui/sheet.tsx
src/lib/API/ProtestInfos.tsx
src/lib/API/VerificationNumber.tsx

> 연관된 이슈를 작성해주세요.
#13 
- Hedaer & Footer 간격 조정
- 시위 상세 간격 조정
- 인증하기 버튼 예외처리
- 시위 상세 컴포넌트에 마크다운 적용 
- 고정값이던 height를 반응형으로 처리하였고 햄버거 클릭시 나오는 리스트에도 반영하였습니다.
- 기존의 UI에서 가독성을 고려하여 조금 수정하였습니다.
- 기존 로직 로그인 유무를 체크하지 않았던 로직에서 엑세스 토큰 없을때 인증하기 버튼을 클릭시 로그인으로 리다이렉트 시키는 로직을 추가하였습니다.
```
const onVerificationClick = () => {
setOpen(true);
};
```
```
const onVerificationClick = () => {
if (!accessToken)
window.location.replace(`${process.env.NEXT_PUBLIC_LOCAL_DEV_URL}/oauth2/authorization/kakao`);
else setOpen(true);
};
```
- MarkdownPreview 라이브러리를 사용하여 간단하게 해결하였습니다.
> 작업한 내용을 작성해주세요.
- 마크다운쪽은 데이터가 마크다운으로 들어오지 않아서 잘 적용되는지 확인은 못했는데 해당 라이브러리 홈페이지에서는 잘 된다고 하는것을 확인하였습니다.!
- 인증하기 로직처리 부분 저렇게 가도 되는지
- 마크다운 컴포넌트를 감싸서 서버 컴포넌트에 넣었는데 그게 맞는지?
- 프리티어 검사하면서인지는 몰라도 그거때문에 너무 느린데 원래 …

[FE] refactor : UI improvements

---

src/app/(with-hamburger-button)/page.tsx
src/app/protest/[id]/page.tsx

Meta tag fixes
- added desired keywords to meta tag for SEO perposes
- google doesn't use keywords anymore but some other sites still references it
- added favicon to protest detail page

feat: added keywords to meta tag

---

src/app/(with-hamburger-button)/page.tsx
src/app/protest/[id]/page.tsx

Added main keywors to meta title tag
- added '오늘의 시위 정보와 집회 정보' to title tag

fix: added main keywords to title meta tag

---

src/components/Verification/Verification.tsx
src/lib/utils.ts

- #21 
- removed use client from utils.ts this occurs formatDate issue
- added window object check logic to avoid being executed from server

refactor: fixed build error issue

---

src/app/@modal/(.)protest/[id]/page.tsx
src/components/Modal/ModalWrapper.tsx

#27 
Fixed issue regarding component type
- to change browser url, client side method is needed
- modal has server component inside
- seperated modal usage codes to modalwrapper component and recieved server component as props

Feature seo keywords

---

.github/workflows/deploy.yml
src/app/(with-hamburger-button)/page.tsx
src/app/protest/[id]/page.tsx
src/components/Footer/Footer.module.css
src/components/Footer/index.tsx
src/components/Header/Header.module.css
src/lib/API/ProtestInfos.tsx
src/lib/API/VerificationNumber.tsx

[FE] style : fix static kakaomap height calculate header footer 

---

src/app/(with-hamburger-button)/layout.tsx
src/components/Protest/protest-list.tsx

- #41 
- add css overflow hidden in protest card parents tag
- remove unnecessary code

[FE] refactor : protest list sidebar closed when user clicked empty space

---

src/apis/protest/index.ts
src/components/Protest/ProtestMapMarker.tsx
src/lib/socket.ts

> 연관된 이슈를 작성해주세요.
> 작업한 내용을 작성해주세요.

style : modify style

---

src/hooks/UseProtestCheerCount.ts

> #59 
- 메인 페이지에서는 모든 시위의 응원 수(`cheer count`)를 폴링하여 가져와야 하지만,  
- 시위 상세 페이지(모달 포함)에서는 해당 시위에 대한 응원 수만 폴링하는 것이 리소스 절약 및 성능 측면에서 효율적임.
- 기존에는 모달이 열려 있어도 전체 시위에 대한 폴링이 계속 진행되어 불필요한 API 요청이 발생하고 있었음.
- 모달이 열려있는지 여부를 판단하는 로직 추가
- 현재 URL path를 이용하여 상세 페이지(`isDetail`) 및 해당 시위 ID 여부(`currentProtestId`)를 확인
- `useQuery`의 `enabled` 옵션 개선
- 메인 페이지: 모든 시위 ID에 대해 폴링 수행
- 상세 페이지: 현재 보고 있는 시위 ID에 대해서만 폴링 수행
- 폴링 인터벌 유지 (3초)  
- 기존처럼 실시간성 유지하면서도 불필요한 API 요청은 방지
```typescript
export const UseProtestCheerCount = (protestId: string) => {
const pathname = usePathname();
const isDetail = pathname.includes('protest');
const currentProtestId = pathname?.split('/').pop();
const { data, isLoading, isError } = useQuery({
queryKey: ['cheer', protestId],
queryFn: () => ProtestCheerCount(protestId),
refetchInterval: …
```

[FE] refactor : Optimize API Polling for Modal View State

---

src/app/protest/[id]/page.tsx
src/components/Protest/ProtestShareButton.tsx

[FE] fix : 아이폰 16pro에서 상세페이지 접속시 화면에 스크롤이 생기는 문제를 해결하고 공유하기 버튼 디자인을 수정한

---

src/app/protest/[id]/page.tsx
src/components/Modal/ModalWrapper.tsx
src/components/Protest/MarkdownWrapper.tsx
src/components/Protest/ProtestDetailInfo.tsx

> #117 
- 특정 시위에서 가로 스크롤이 생기는 문제를 해결하였습니다.
- 폰트크기와 태그 및 내용 구분을 통한 UX를 향상시켰습니다.

[FE] refactor : 특정 시위 상세 모달에서만 스크롤이 생기는 문제를 해결한다

---

src/hooks/useThrottledHeatmapUpdate.ts

> 연관된 이슈를 작성해주세요.
- 불필요해진 zoom level 검사 로직을 제거한다
- 불필요한 주석을 제거한다

[FE] chore : 불필요한 조건을 제거하고 불필요한 주석 또한 제거한다

---

src/hooks/useHeatMap.ts

> #138 
- https://www.maeil-mail.kr/question/37
- 위 내용을 보던중 문득 이런 생각이 들었습니다. 스크립트 다운로드 및 적용 로직이 올바른가?
- onload를 통해 이미 스크립트 다운로드 성공 후 실행이 보장되어 있기에 불필요한 코드를 삭제하였습니다.

[FE] refactor : 히트맵 로직에서 불필요한 로직을 삭제한다

---

src/hooks/useHeatMap.ts

- heatmap script sli hash를 env로 분리한다

[FE] refactor : heatmap script sli hash를 env로 분리한다

---

src/hooks/useHeatMap.ts

[FE] chore : main 브랜치에 동기화를 진행한다
